[build]
  publish = "."
  command = ""

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/vendor/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
